#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : syndication
Version  : 18.08.0
Release  : 1
URL      : https://download.kde.org/stable/applications/18.08.0/src/syndication-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/syndication-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/syndication-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause LGPL-2.1
Requires: syndication-lib
Requires: syndication-license
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde

%description
This directory contains valid feeds that are known to cause problems with libsyndication. They are separated from
the regression tests as they shouldn't be executed in "make test" runs. As soon as they succeed, move them to the
respective regression test folder.

%package dev
Summary: dev components for the syndication package.
Group: Development
Requires: syndication-lib
Provides: syndication-devel

%description dev
dev components for the syndication package.


%package lib
Summary: lib components for the syndication package.
Group: Libraries
Requires: syndication-license

%description lib
lib components for the syndication package.


%package license
Summary: license components for the syndication package.
Group: Default

%description license
license components for the syndication package.


%prep
%setup -q -n syndication-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535239554
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535239554
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/syndication
cp COPYING.BSD %{buildroot}/usr/share/doc/syndication/COPYING.BSD
cp COPYING.LIB %{buildroot}/usr/share/doc/syndication/COPYING.LIB
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/Syndication/Syndication/AbstractParser
/usr/include/KF5/Syndication/Syndication/Atom/Atom
/usr/include/KF5/Syndication/Syndication/Atom/Category
/usr/include/KF5/Syndication/Syndication/Atom/Constants
/usr/include/KF5/Syndication/Syndication/Atom/Content
/usr/include/KF5/Syndication/Syndication/Atom/Document
/usr/include/KF5/Syndication/Syndication/Atom/Entry
/usr/include/KF5/Syndication/Syndication/Atom/Generator
/usr/include/KF5/Syndication/Syndication/Atom/Link
/usr/include/KF5/Syndication/Syndication/Atom/Parser
/usr/include/KF5/Syndication/Syndication/Atom/Person
/usr/include/KF5/Syndication/Syndication/Atom/Source
/usr/include/KF5/Syndication/Syndication/Category
/usr/include/KF5/Syndication/Syndication/Constants
/usr/include/KF5/Syndication/Syndication/DataRetriever
/usr/include/KF5/Syndication/Syndication/DocumentSource
/usr/include/KF5/Syndication/Syndication/DocumentVisitor
/usr/include/KF5/Syndication/Syndication/ElementWrapper
/usr/include/KF5/Syndication/Syndication/Enclosure
/usr/include/KF5/Syndication/Syndication/Feed
/usr/include/KF5/Syndication/Syndication/Global
/usr/include/KF5/Syndication/Syndication/Image
/usr/include/KF5/Syndication/Syndication/Item
/usr/include/KF5/Syndication/Syndication/Loader
/usr/include/KF5/Syndication/Syndication/Mapper
/usr/include/KF5/Syndication/Syndication/ParserCollection
/usr/include/KF5/Syndication/Syndication/Person
/usr/include/KF5/Syndication/Syndication/Rdf/ContentVocab
/usr/include/KF5/Syndication/Syndication/Rdf/Document
/usr/include/KF5/Syndication/Syndication/Rdf/DublinCore
/usr/include/KF5/Syndication/Syndication/Rdf/DublinCoreVocab
/usr/include/KF5/Syndication/Syndication/Rdf/Image
/usr/include/KF5/Syndication/Syndication/Rdf/Item
/usr/include/KF5/Syndication/Syndication/Rdf/Literal
/usr/include/KF5/Syndication/Syndication/Rdf/Model
/usr/include/KF5/Syndication/Syndication/Rdf/ModelMaker
/usr/include/KF5/Syndication/Syndication/Rdf/Node
/usr/include/KF5/Syndication/Syndication/Rdf/NodeVisitor
/usr/include/KF5/Syndication/Syndication/Rdf/Parser
/usr/include/KF5/Syndication/Syndication/Rdf/Property
/usr/include/KF5/Syndication/Syndication/Rdf/Rdf
/usr/include/KF5/Syndication/Syndication/Rdf/RdfVocab
/usr/include/KF5/Syndication/Syndication/Rdf/Resource
/usr/include/KF5/Syndication/Syndication/Rdf/ResourceWrapper
/usr/include/KF5/Syndication/Syndication/Rdf/RssVocab
/usr/include/KF5/Syndication/Syndication/Rdf/Sequence
/usr/include/KF5/Syndication/Syndication/Rdf/Statement
/usr/include/KF5/Syndication/Syndication/Rdf/SyndicationInfo
/usr/include/KF5/Syndication/Syndication/Rdf/SyndicationVocab
/usr/include/KF5/Syndication/Syndication/Rdf/TextInput
/usr/include/KF5/Syndication/Syndication/Rss2/Category
/usr/include/KF5/Syndication/Syndication/Rss2/Cloud
/usr/include/KF5/Syndication/Syndication/Rss2/Document
/usr/include/KF5/Syndication/Syndication/Rss2/Enclosure
/usr/include/KF5/Syndication/Syndication/Rss2/Image
/usr/include/KF5/Syndication/Syndication/Rss2/Item
/usr/include/KF5/Syndication/Syndication/Rss2/Parser
/usr/include/KF5/Syndication/Syndication/Rss2/Rss2
/usr/include/KF5/Syndication/Syndication/Rss2/Source
/usr/include/KF5/Syndication/Syndication/Rss2/TextInput
/usr/include/KF5/Syndication/Syndication/SpecificDocument
/usr/include/KF5/Syndication/Syndication/SpecificItem
/usr/include/KF5/Syndication/Syndication/SpecificItemVisitor
/usr/include/KF5/Syndication/Syndication/Syndication
/usr/include/KF5/Syndication/Syndication/Tools
/usr/include/KF5/Syndication/syndication/abstractparser.h
/usr/include/KF5/Syndication/syndication/atom/atom.h
/usr/include/KF5/Syndication/syndication/atom/category.h
/usr/include/KF5/Syndication/syndication/atom/constants.h
/usr/include/KF5/Syndication/syndication/atom/content.h
/usr/include/KF5/Syndication/syndication/atom/document.h
/usr/include/KF5/Syndication/syndication/atom/entry.h
/usr/include/KF5/Syndication/syndication/atom/generator.h
/usr/include/KF5/Syndication/syndication/atom/link.h
/usr/include/KF5/Syndication/syndication/atom/parser.h
/usr/include/KF5/Syndication/syndication/atom/person.h
/usr/include/KF5/Syndication/syndication/atom/source.h
/usr/include/KF5/Syndication/syndication/category.h
/usr/include/KF5/Syndication/syndication/constants.h
/usr/include/KF5/Syndication/syndication/dataretriever.h
/usr/include/KF5/Syndication/syndication/documentsource.h
/usr/include/KF5/Syndication/syndication/documentvisitor.h
/usr/include/KF5/Syndication/syndication/elementwrapper.h
/usr/include/KF5/Syndication/syndication/enclosure.h
/usr/include/KF5/Syndication/syndication/feed.h
/usr/include/KF5/Syndication/syndication/global.h
/usr/include/KF5/Syndication/syndication/image.h
/usr/include/KF5/Syndication/syndication/item.h
/usr/include/KF5/Syndication/syndication/loader.h
/usr/include/KF5/Syndication/syndication/mapper.h
/usr/include/KF5/Syndication/syndication/parsercollection.h
/usr/include/KF5/Syndication/syndication/person.h
/usr/include/KF5/Syndication/syndication/rdf/contentvocab.h
/usr/include/KF5/Syndication/syndication/rdf/document.h
/usr/include/KF5/Syndication/syndication/rdf/dublincore.h
/usr/include/KF5/Syndication/syndication/rdf/dublincorevocab.h
/usr/include/KF5/Syndication/syndication/rdf/image.h
/usr/include/KF5/Syndication/syndication/rdf/item.h
/usr/include/KF5/Syndication/syndication/rdf/literal.h
/usr/include/KF5/Syndication/syndication/rdf/model.h
/usr/include/KF5/Syndication/syndication/rdf/modelmaker.h
/usr/include/KF5/Syndication/syndication/rdf/node.h
/usr/include/KF5/Syndication/syndication/rdf/nodevisitor.h
/usr/include/KF5/Syndication/syndication/rdf/parser.h
/usr/include/KF5/Syndication/syndication/rdf/property.h
/usr/include/KF5/Syndication/syndication/rdf/rdf.h
/usr/include/KF5/Syndication/syndication/rdf/rdfvocab.h
/usr/include/KF5/Syndication/syndication/rdf/resource.h
/usr/include/KF5/Syndication/syndication/rdf/resourcewrapper.h
/usr/include/KF5/Syndication/syndication/rdf/rssvocab.h
/usr/include/KF5/Syndication/syndication/rdf/sequence.h
/usr/include/KF5/Syndication/syndication/rdf/statement.h
/usr/include/KF5/Syndication/syndication/rdf/syndicationinfo.h
/usr/include/KF5/Syndication/syndication/rdf/syndicationvocab.h
/usr/include/KF5/Syndication/syndication/rdf/textinput.h
/usr/include/KF5/Syndication/syndication/rss2/category.h
/usr/include/KF5/Syndication/syndication/rss2/cloud.h
/usr/include/KF5/Syndication/syndication/rss2/document.h
/usr/include/KF5/Syndication/syndication/rss2/enclosure.h
/usr/include/KF5/Syndication/syndication/rss2/image.h
/usr/include/KF5/Syndication/syndication/rss2/item.h
/usr/include/KF5/Syndication/syndication/rss2/parser.h
/usr/include/KF5/Syndication/syndication/rss2/rss2.h
/usr/include/KF5/Syndication/syndication/rss2/source.h
/usr/include/KF5/Syndication/syndication/rss2/textinput.h
/usr/include/KF5/Syndication/syndication/specificdocument.h
/usr/include/KF5/Syndication/syndication/specificitem.h
/usr/include/KF5/Syndication/syndication/specificitemvisitor.h
/usr/include/KF5/Syndication/syndication/syndication.h
/usr/include/KF5/Syndication/syndication/syndication_export.h
/usr/include/KF5/Syndication/syndication/tools.h
/usr/include/KF5/syndication_version.h
/usr/lib64/cmake/KF5Syndication/KF5SyndicationConfig.cmake
/usr/lib64/cmake/KF5Syndication/KF5SyndicationConfigVersion.cmake
/usr/lib64/cmake/KF5Syndication/KF5SyndicationTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5Syndication/KF5SyndicationTargets.cmake
/usr/lib64/libKF5Syndication.so
/usr/lib64/qt5/mkspecs/modules/qt_Syndication.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5Syndication.so.5
/usr/lib64/libKF5Syndication.so.5.9.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/syndication/COPYING.BSD
/usr/share/doc/syndication/COPYING.LIB
